Solaris fcntl() returns 'Bad file number' when an exclusive lock is requested
on non-writable file.

This is a Solaris specific patch.

--- django-5.2.6/django/test/testcases.py
+++ django-5.2.6/django/test/testcases.py
@@ -1884,7 +1884,7 @@ class SerializeMixin:
 
     @classmethod
     def setUpClass(cls):
-        cls._lockfile = open(cls.lockfile)
+        cls._lockfile = open(cls.lockfile, 'r+')
         cls.addClassCleanup(cls._lockfile.close)
         locks.lock(cls._lockfile, locks.LOCK_EX)
         super().setUpClass()
--- django-5.2.6/tests/files/tests.py
+++ django-5.2.6/tests/files/tests.py
@@ -189,6 +189,7 @@ class FileTests(unittest.TestCase):
             test_file.seek(0)
             self.assertEqual(test_file.read(), (content * 2).encode())
 
+    @unittest.skip("Case assumptions are not correct on Solaris")
     def test_exclusive_lock(self):
         file_path = Path(__file__).parent / "test.png"
         with open(file_path) as f1, open(file_path) as f2:
